declare const process: { env: Record<string, string | undefined> };

import type {
  ServerContext,
  GetCountryIntelBriefRequest,
  GetCountryIntelBriefResponse,
} from '../../../../src/generated/server/worldmonitor/intelligence/v1/service_server';

import { cachedFetchJson } from '../../../_shared/redis';
import { UPSTREAM_TIMEOUT_MS, TIER1_COUNTRIES } from './_shared';

// ========================================================================
// Constants
// ========================================================================
const INTEL_CACHE_TTL = 43200; // 12 hours
// ========================================================================
// RPC handler
// ========================================================================

export async function getCountryIntelBrief(
  _ctx: ServerContext,
  req: GetCountryIntelBriefRequest,
): Promise<GetCountryIntelBriefResponse> {
  const empty: GetCountryIntelBriefResponse = {
    countryCode: req.countryCode,
    countryName: '',
    brief: '',
    model: 'gemini-2.5-pro',
    generatedAt: Date.now(),
  };

  const geminiApiKey = process.env.GEMINI_API_KEY;
  if (!geminiApiKey) return empty;

  const cacheKey = `ci-sebuf:v2:${req.countryCode}`;
  const countryName = TIER1_COUNTRIES[req.countryCode] || req.countryCode;
  const now = new Date();
  const dateStr = `${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}-${now.getFullYear()}`;

  const systemPrompt = `Provide a comprehensive country situation brief. Current date: ${dateStr}.

Write a concise intelligence brief for the requested country covering:
1. Heading - Must be exactly:
   <Country Name> Intelligence Briefing
   Dated: ${dateStr}
2. Current Situation - what is happening right now
3. Military & Security Posture
4. Key Risk Factors
5. Regional Context
6. Outlook & Watch Items
7. Sources - list the relevant news feeds used, if available, and provide the specific dates of the sourced data to assure the user of its recency.

Rules:
- SEARCH REQUIREMENT: Use web search tools to find the latest verified news (last 24-72 hours) for the designated country. Rely exclusively on reputable news agencies (e.g., BBC, NPR, AP, Reuters).
- SOURCE RESTRICTION: Exclude whitehouse.gov and its subdomains entirely.
- ACCURACY: Report only verified data. If data is unavailable, output exactly: "NO RELIABLE DATA AT THIS TIME" with your reasoning.
- DIRECTNESS: Start immediately with the Heading. Omit all preambles, courtesy text, and technical markdown formatting (e.g., no code blocks).
- STYLE: Use plain language, 4-5 paragraphs, 250-350 words. Be specific and analytical.
- DISCLAIMER: At the end of every briefing, append exactly: "DISCLAIMER: This briefing was generated by an AI assistant. AI can make mistakes. Be sure to cross-reference the information provided with reputable news sources."`;

  const result = await cachedFetchJson<GetCountryIntelBriefResponse | null>(cacheKey, INTEL_CACHE_TTL, async () => {
    try {
      const geminiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-pro:generateContent?key=${geminiApiKey}`;
      const resp = await fetch(geminiUrl, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          systemInstruction: {
            parts: [{ text: systemPrompt }]
          },
          contents: [{
            role: 'user',
            parts: [{ text: `### Target Country ###\n${countryName} (${req.countryCode})` }]
          }],
          tools: [{
            googleSearch: {}
          }],
          generationConfig: {
            temperature: 0.7,
            maxOutputTokens: 1024,
            topP: 0.8
          }
        }),
        signal: AbortSignal.timeout(UPSTREAM_TIMEOUT_MS),
      });

      if (resp.ok) {
        const data = (await resp.json()) as { candidates?: Array<{ content?: { parts?: Array<{ text?: string }> } }> };
        const brief = data.candidates?.[0]?.content?.parts?.[0]?.text?.trim() || '';
        if (brief) {
          return {
            countryCode: req.countryCode,
            countryName,
            brief,
            model: 'gemini-2.5-pro',
            generatedAt: Date.now(),
          };
        }
      }
    } catch {
      // Fall through to null if it fails
    }

    return null;
  });

  return result || empty;
}
