export interface CuratedCountryConfig {
  name: string;
  scoringKeywords: string[];
  searchAliases: string[];
  baselineRisk: number;
  eventMultiplier: number;
}

export const CURATED_COUNTRIES: Record<string, CuratedCountryConfig> = {
  US: {
    name: 'United States',
    scoringKeywords: ['united states', 'usa', 'america', 'washington', 'biden', 'trump', 'pentagon', 'us'],
    searchAliases: ['united states', 'american', 'washington', 'pentagon', 'white house', 'usa', 'america', 'biden', 'trump', 'us'],
    baselineRisk: 5,
    eventMultiplier: 0.3,
  },
  RU: {
    name: 'Russia',
    scoringKeywords: ['russia', 'moscow', 'kremlin', 'putin', 'ru'],
    searchAliases: ['russia', 'russian', 'moscow', 'kremlin', 'putin', 'ukraine war', 'ru'],
    baselineRisk: 35,
    eventMultiplier: 2.0,
  },
  CN: {
    name: 'China',
    scoringKeywords: ['china', 'beijing', 'xi jinping', 'prc', 'cn'],
    searchAliases: ['china', 'chinese', 'beijing', 'taiwan strait', 'south china sea', 'xi jinping', 'cn'],
    baselineRisk: 25,
    eventMultiplier: 2.5,
  },
  UA: {
    name: 'Ukraine',
    scoringKeywords: ['ukraine', 'kyiv', 'zelensky', 'donbas', 'ua'],
    searchAliases: ['ukraine', 'ukrainian', 'kyiv', 'zelensky', 'zelenskyy', 'ua'],
    baselineRisk: 50,
    eventMultiplier: 0.8,
  },
  IR: {
    name: 'Iran',
    scoringKeywords: ['iran', 'tehran', 'khamenei', 'irgc', 'ir'],
    searchAliases: ['iran', 'iranian', 'tehran', 'persian', 'irgc', 'khamenei', 'ir'],
    baselineRisk: 40,
    eventMultiplier: 2.0,
  },
  IL: {
    name: 'Israel',
    scoringKeywords: ['israel', 'tel aviv', 'netanyahu', 'idf', 'gaza', 'il'],
    searchAliases: ['israel', 'israeli', 'gaza', 'hamas', 'hezbollah', 'netanyahu', 'idf', 'west bank', 'tel aviv', 'jerusalem', 'il'],
    baselineRisk: 45,
    eventMultiplier: 0.7,
  },
  TW: {
    name: 'Taiwan',
    scoringKeywords: ['taiwan', 'taipei', 'tw'],
    searchAliases: ['taiwan', 'taiwanese', 'taipei', 'tw'],
    baselineRisk: 30,
    eventMultiplier: 1.5,
  },
  KP: {
    name: 'North Korea',
    scoringKeywords: ['north korea', 'pyongyang', 'kim jong', 'kp'],
    searchAliases: ['north korea', 'pyongyang', 'kim jong', 'kp'],
    baselineRisk: 45,
    eventMultiplier: 3.0,
  },
  SA: {
    name: 'Saudi Arabia',
    scoringKeywords: ['saudi arabia', 'riyadh', 'mbs', 'sa'],
    searchAliases: ['saudi', 'riyadh', 'mbs', 'sa'],
    baselineRisk: 20,
    eventMultiplier: 2.0,
  },
  TR: {
    name: 'Turkey',
    scoringKeywords: ['turkey', 'ankara', 'erdogan', 'tr'],
    searchAliases: ['turkey', 'turkish', 'ankara', 'erdogan', 'türkiye', 'tr'],
    baselineRisk: 25,
    eventMultiplier: 1.2,
  },
  PL: {
    name: 'Poland',
    scoringKeywords: ['poland', 'warsaw', 'pl'],
    searchAliases: ['poland', 'polish', 'warsaw', 'pl'],
    baselineRisk: 10,
    eventMultiplier: 0.8,
  },
  DE: {
    name: 'Germany',
    scoringKeywords: ['germany', 'berlin', 'de'],
    searchAliases: ['germany', 'german', 'berlin', 'de'],
    baselineRisk: 5,
    eventMultiplier: 0.5,
  },
  FR: {
    name: 'France',
    scoringKeywords: ['france', 'paris', 'macron', 'fr'],
    searchAliases: ['france', 'french', 'paris', 'macron', 'fr'],
    baselineRisk: 10,
    eventMultiplier: 0.6,
  },
  GB: {
    name: 'United Kingdom',
    scoringKeywords: ['britain', 'uk', 'london', 'starmer', 'gb'],
    searchAliases: ['united kingdom', 'british', 'london', 'uk ', 'gb'],
    baselineRisk: 5,
    eventMultiplier: 0.5,
  },
  IN: {
    name: 'India',
    scoringKeywords: ['india', 'delhi', 'modi', 'in'],
    searchAliases: ['india', 'indian', 'new delhi', 'modi', 'in'],
    baselineRisk: 20,
    eventMultiplier: 0.8,
  },
  PK: {
    name: 'Pakistan',
    scoringKeywords: ['pakistan', 'islamabad', 'pk'],
    searchAliases: ['pakistan', 'pakistani', 'islamabad', 'pk'],
    baselineRisk: 35,
    eventMultiplier: 1.5,
  },
  SY: {
    name: 'Syria',
    scoringKeywords: ['syria', 'damascus', 'assad', 'sy'],
    searchAliases: ['syria', 'syrian', 'damascus', 'assad', 'sy'],
    baselineRisk: 50,
    eventMultiplier: 0.7,
  },
  YE: {
    name: 'Yemen',
    scoringKeywords: ['yemen', 'sanaa', 'houthi', 'ye'],
    searchAliases: ['yemen', 'houthi', 'sanaa', 'ye'],
    baselineRisk: 50,
    eventMultiplier: 0.7,
  },
  MM: {
    name: 'Myanmar',
    scoringKeywords: ['myanmar', 'burma', 'rangoon', 'mm'],
    searchAliases: ['myanmar', 'burmese', 'burma', 'rangoon', 'mm'],
    baselineRisk: 45,
    eventMultiplier: 1.8,
  },
  VE: {
    name: 'Venezuela',
    scoringKeywords: ['venezuela', 'caracas', 'maduro', 've'],
    searchAliases: ['venezuela', 'venezuelan', 'caracas', 'maduro', 've'],
    baselineRisk: 40,
    eventMultiplier: 1.8,
  },
  BR: {
    name: 'Brazil',
    scoringKeywords: ['brazil', 'brasilia', 'lula', 'bolsonaro', 'br'],
    searchAliases: ['brazil', 'brazilian', 'brasilia', 'lula', 'bolsonaro', 'br'],
    baselineRisk: 15,
    eventMultiplier: 0.6,
  },
  AE: {
    name: 'United Arab Emirates',
    scoringKeywords: ['uae', 'emirates', 'dubai', 'abu dhabi', 'ae'],
    searchAliases: ['united arab emirates', 'uae', 'emirati', 'dubai', 'abu dhabi', 'ae'],
    baselineRisk: 10,
    eventMultiplier: 1.5,
  },
  MX: {
    name: 'Mexico',
    scoringKeywords: ['mexico', 'mexican', 'amlo', 'sheinbaum', 'cartel', 'sinaloa', 'jalisco', 'cjng', 'tijuana', 'juarez', 'sedena', 'mx'],
    searchAliases: ['mexico', 'mexican', 'amlo', 'sheinbaum', 'cartel', 'sinaloa', 'jalisco', 'cjng', 'tijuana', 'juarez', 'sedena', 'fentanyl', 'narco', 'mx'],
    baselineRisk: 35,
    eventMultiplier: 1.0,
  },
  KR: {
    name: 'South Korea',
    scoringKeywords: ['south korea', 'seoul', 'kr', 'rok'],
    searchAliases: ['south korea', 'seoul', 'kr', 'rok', 'korean'],
    baselineRisk: 15,
    eventMultiplier: 1.0,
  },
  CU: {
    name: 'Cuba',
    scoringKeywords: ['cuba', 'havana', 'cu'],
    searchAliases: ['cuba', 'cuban', 'havana', 'cu'],
    baselineRisk: 25,
    eventMultiplier: 1.2,
  },
  IQ: {
    name: 'Iraq',
    scoringKeywords: ['iraq', 'iraqi', 'baghdad', 'iq'],
    searchAliases: ['iraq', 'iraqi', 'baghdad', 'iq'],
    baselineRisk: 35,
    eventMultiplier: 1.0,
  },
  AF: {
    name: 'Afghanistan',
    scoringKeywords: ['afghanistan', 'afghan', 'kabul', 'taliban', 'af'],
    searchAliases: ['afghanistan', 'afghan', 'kabul', 'taliban', 'af'],
    baselineRisk: 15,
    eventMultiplier: 1.0,
  },
  LB: {
    name: 'Lebanon',
    scoringKeywords: ['lebanon', 'lebanese', 'beirut', 'lb'],
    searchAliases: ['lebanon', 'lebanese', 'beirut', 'lb'],
    baselineRisk: 15,
    eventMultiplier: 1.0,
  },
  EG: {
    name: 'Egypt',
    scoringKeywords: ['egypt', 'egyptian', 'cairo', 'suez', 'eg'],
    searchAliases: ['egypt', 'egyptian', 'cairo', 'suez', 'eg'],
    baselineRisk: 15,
    eventMultiplier: 1.0,
  },
  JP: {
    name: 'Japan',
    scoringKeywords: ['japan', 'japanese', 'tokyo', 'jp'],
    searchAliases: ['japan', 'japanese', 'tokyo', 'jp'],
    baselineRisk: 15,
    eventMultiplier: 1.0,
  },
  QA: {
    name: 'Qatar',
    scoringKeywords: ['qatar', 'qatari', 'doha', 'qa'],
    searchAliases: ['qatar', 'qatari', 'doha', 'qa'],
    baselineRisk: 15,
    eventMultiplier: 1.0,
  },
};

export const TIER1_COUNTRIES: Record<string, string> = {
  US: 'United States',
  RU: 'Russia',
  CN: 'China',
  UA: 'Ukraine',
  IR: 'Iran',
  IL: 'Israel',
  TW: 'Taiwan',
  KP: 'North Korea',
  SA: 'Saudi Arabia',
  TR: 'Turkey',
  PL: 'Poland',
  DE: 'Germany',
  FR: 'France',
  GB: 'United Kingdom',
  IN: 'India',
  PK: 'Pakistan',
  SY: 'Syria',
  YE: 'Yemen',
  MM: 'Myanmar',
  VE: 'Venezuela',
  BR: 'Brazil',
  AE: 'United Arab Emirates',
  MX: 'Mexico',
  ET: 'Ethiopia',
  AQ: 'Antarctica',
  SE: 'Sweden',
  LA: 'Laos',
  KN: 'Saint Kitts and Nevis',
  AI: 'Anguilla',
  MS: 'Montserrat',
  XC: 'Northern Cyprus',
  XS: 'Somaliland',
  NI: 'Nicaragua',
  PA: 'Panama',
  SR: 'Suriname',
  SZ: 'Eswatini',
  NA: 'Namibia',
  AO: 'Angola',
  BI: 'Burundi',
  GA: 'Gabon',
  BJ: 'Benin',
  TG: 'Togo',
  CI: 'The Ivory Coast',
  SL: 'Sierra Leone',
  SN: 'Senegal',
  GW: 'Guinea-Bissau',
  MA: 'Morocco',
  ML: 'Mali',
  TD: 'Chad',
  TN: 'Tunisia',
  SS: 'South Sudan',
  ME: 'Montenegro',
  KW: 'Kuwait',
  MC: 'Monaco',
  IS: 'Iceland',
  SK: 'Slovakia',
  BA: 'Bosnia and Herzegovina',
  NC: 'New Caledonia',
  VU: 'Vanuatu',
  FO: 'Faroe Islands',
  FK: 'Falkland Islands',
  KY: 'the Cayman Islands',
  BS: 'the Bahamas',
  TC: 'Turks and Caicos Islands',
  BM: 'Bermuda',
  DM: 'Dominica',
  LC: 'Saint Lucia',
  BB: 'Barbados',
  VC: 'St Vincent and Grenadines',
  CV: 'Cape Verde',
  GS: 'South Georgia & South Sandwich Islands',
};

export const DEFAULT_BASELINE_RISK = 15;
export const DEFAULT_EVENT_MULTIPLIER = 1.0;

export const HOTSPOT_COUNTRY_MAP: Record<string, string | string[]> = {
  tehran: 'IR', moscow: 'RU', beijing: 'CN', kyiv: 'UA', taipei: 'TW',
  telaviv: 'IL', pyongyang: 'KP', sanaa: 'YE', riyadh: 'SA', ankara: 'TR',
  damascus: 'SY', caracas: 'VE', dc: 'US', london: 'GB',
  brussels: 'BE', baghdad: 'IQ', beirut: 'LB', doha: 'QA', abudhabi: 'AE',
  mexico: 'MX', nuuk: 'GL', sahel: ['ML', 'NE', 'BF'], haiti: 'HT',
  horn_africa: ['ET', 'SO', 'SD'], silicon_valley: 'US', wall_street: 'US',
  houston: 'US', cairo: 'EG',
};

export function getHotspotCountries(hotspotId: string): string[] {
  const val = HOTSPOT_COUNTRY_MAP[hotspotId];
  if (!val) return [];
  return Array.isArray(val) ? val : [val];
}
